const strings = {
  Name: "Name",
  TopicsPosts: "Topics/Posts",
  LastPost: "Last Post",
  Topics: "Topics",
  Posts: "Posts",
  Close: "Close",
  NewForum: "New Forum",
  Confirm: "Confirm",
  Delete: "Delete",
  Cancel: "Cancel",
  Forum: "Forum",
  EditForum: "Edit Forum",
  TitleRequired: "Title is required",
  DescriptionRequired: "Description is required",
  Save: "Save",
  Add: "Add",
  Update: "Update",
  ConfirmDelete: "Are you sure you want to delete the",
  Wait: "Wait...",
  Loading: "Loading...",
  RepliesViews: "Replies/Views",
  Replies: "Replies",
  Views: "Views",
  NewTopic: "New Topic",
  Topic: "Topic",
  By: "By",
  Forums: "Forums",
  EditPost: "Edit Post",
  ReplyPost: "Reply Post",
  EditTopic: "Edit Topic",
  LoadMore: "Load More",
  Created: "Created",
  of: "of",
  Like: "Like",
  Login: "Login",
  Email: "Email",
  Password: "Password",
  EmailRequired: "Email is Required",
  PasswordRequired: "Password is Required",
  InvalidEmail: "Invalid E-mail address",
  Register: "Register",
  Logout: "Logout",
  AuthError:
    "Authentication is required. You need to (re)login or register.",
  RegError: "Could not be registered",
  ErrorPermission: "You do not have permission for this action",
  Reply: "Reply",
  Liked: "You liked the post",
  UnLiked: "You unliked the post",
  Updated: "Updated",
  Title: 'Title',
  Description: "Description"
};

export default strings;
